services:
  efw:
    build:
      context: .
      dockerfile: Dockerfile
    # mount the current directory to /app in the container
    volumes:
      - ./:/app
    # cap abilities to allow network management
    # this is necessary for modifying nftables
    cap_add:
      - NET_ADMIN
  debian:
    build:
      context: .
      dockerfile: debian.Dockerfile